config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :posts do 
    resources :likes, only: [:create, :new, :destroy]
  end

  root 'sessions#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/posts/:id' => 'posts#add_comment'
  post '/search/posts' => 'searchs#search_posts'
  post '/search/user_posts' => 'searchs#search_posts_within_user'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :posts
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :tag_posts
    has_many :tags, through: :tag_posts
    has_many :post_likes
    has_many :comments
    belongs_to :user
    belongs_to :language
    has_many :likes, dependent: :destroy
    accepts_nested_attributes_for :tags

    validates_presence_of :title, :content, :language, :tags
    validates :title, :length => {minimum: 5}
    validates :content, :length => {minimum:5}

    def show_tags
        return_string = ""
        tags = self.tags
        tags.each do |tag|
            return_string += "#{tag.name}, "       
        end
        return_string.strip.chop #getting rid of the last whitespace and the last , using chop
    end

    def self.order_posts(column)
        posts = Post.all.sort_by do |p| 
            if column == "author"
                p.user.name.downcase
            elsif column == "title"
                p.title.downcase
            elsif column == "likes"
                p.likes.count
            elsif column == "language"
                p.language.name.downcase
            else
                p.id
            end
        end
        posts      
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_posts
    has_many :posts, through: :tag_posts
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
    belongs_to :post
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments
    has_many :post_likes
    has_many :likes, dependent: :destroy
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception


    def current_user
        @user = (User.find_by(id: session[:user_id]) || User.new)
    end

    def logged_in?
        current_user.id != nil
    end

    def require_logged_in
        #go to the login page unless logged_in be false
        if !logged_in?
            return redirect_to(controller: 'sessions', action: 'new')
        end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    before_action :find_post, only: [:show, :create]
    before_action :find_like, only: [:destroy]

    def create 
        # current_user = current_user
        if already_liked? 
           
        else
        @post.likes.create(user_id: current_user.id)
        end
        redirect_to post_path(@post)
    end

    def destroy 
        if !(already_liked?)
            flash[:notice] = "cannot unlike"
        else
            @like.destroy
        end
        redirect_to post_path(@post)
    end

    private 

    def find_like 
        @post = Post.find(params[:post_id])
        @like = @post.likes.find(params[:id])
    end

    def already_liked? 
        Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end

    def find_post 
        @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_logged_in
    before_action :set_post, only: [:show, :add_comment, :edit, :update]
   
   
    def index 
        @posts = params[:sort] ? Post.order_posts(params[:sort]) : Post.all
        @tags = Tag.all
    end

    def show 
        @comments = @post.comments
        @user = User.find(session[:user_id])
    end

    def new 
        @post = Post.new
        @languages = Language.all
        @tags = Tag.all
    end

    def create 
        
        @post = Post.new(allowed_params)
        @post.user_id = session[:user_id]
         @post.tags.build(name: "add tag")
        
        if @post.save
        
        flash[:notice]  =  "post successfully created"
        redirect_to @post
        else 
         
            @languages = Language.all
            @tags = Tag.all
            flash[:errors] = @post.errors.full_messages 
        
            render :new

        end
    end

    def add_comment
        comment = Comment.new(post_id: @post.id, user_id: session[:user_id], content: params[:comment])
        if comment.save
            redirect_to @post
        else
            flash[:errors] = @post.errors.full_messages
            redirect_to @post
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    def edit 

        @languages = Language.all
        @tags = Tag.all
        
    end

    def update 
        @post.update(allowed_params)
        redirect_to @post
    end

    private 

    def set_post
        @post = Post.find(params[:id])
    end

    def allowed_params 
        params.require(:post).permit(:title, :description, :content, :language_id, tag_ids:[], tags_attributes:[:name])
    end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
    def search_posts
        if params[:title].blank?
            flash[:errors] = ["Empty search field"]
            return redirect_to root_path 
        else
            param = params[:title].downcase
            @posts = Post.all.where("lower(title) LIKE ?", "%#{param}%")
            render 'posts/index' 
        end  
    end

    def search_posts_within_user
        if params[:title].blank?
            flash[:errors] = ["Empty search field"]
            return redirect_to root_path 
        else
            param = params[:title].downcase
            @user = User.find(session[:user_id])
            @posts = @user.posts
            @posts = @posts.all.where("lower(title) LIKE ?", "%#{param}%")
            render 'posts/index'
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only: :home
  
    def home
        @user = User.find(session[:user_id])
        @posts = @user.posts 
         
    end
    
    def new
        @user = User.new
    end

    def create
        user = User.find_by(name: params[:user][:name])
        user = user.try(:authenticate, params[:user][:password])
        if !user
            flash[:error] = "User / password invalid"
            @user = User.new
            return redirect_to(controller: 'sessions', action: 'new')
        end
        session[:user_id] = user.id
        @user = user
        redirect_to controller: 'sessions', action: 'home'
    end

    def destroy
        session.delete :user_id
        redirect_to '/'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:index]
  before_action :set_user, only: [:show, :index]
  
  def new
    if logged_in?
      redirect_to controller: 'sessions', action: 'home'
    end
    @user = User.new
  end

  def index
    if @user.is_admin
      @users = User.all
    else
      redirect_to controller: 'sessions', action: 'home'
    end
    
  end
  
  def create
    @user = User.create(user_params)
    flash[:error] = "Successful"
    return redirect_to controller: 'users', action: 'new' unless @user.save
    session[:user_id] = @user.id
    redirect_to controller: 'sessions', action: 'home'
  end

  def show 
      @user = User.find(params[:id]) #override the set_user method
      @posts = @user.posts
  end

  private  
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def set_user 
    @user = User.find(session[:user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code Repository</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
 <style>
.bar-list {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #1E90FF;
}

li {
  float: left;
}




#outset {
  border-style: outset;
    border-width: 5px;
    width: 50%;
    position: auto;

  }

.like-button {

}

.container-show {
  margin: 2px 100px 75px 40px;
    border: ;
    padding: 0px 0px 0px 0px;

}


li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #00BFFF;
}
</style>
 
  </head>

  <body>
  <%if !!session[:user_id]%>
        <ul class="bar-list">
           <li class="">
            <a class="nav-link" href='/'>User: <%=User.find(session[:user_id]).name%></a>
          </li>

          <li class="">
            <a class="nav-link" href="/">Home</a>
          </li>

          <%if User.find(session[:user_id]).is_admin%>
          <li class="">
            <a class="nav-link" href="/users">Show All Users</a>
          </li>
          <%end%>

          <li class="">
            <a class="nav-link" href="/posts">Show All Posts</a>
          </li>
          <li class="">
      
            <a class="nav-link" href="/posts/new">Create New Post</a>
          </li>

          <li>
            <%= form_tag ({controller: 'searchs', action: 'search_posts', method: 'post'}) do %>
              <input name='title' class="form-control mr-sm-2" type="search" placeholder="Search for Posts" aria-label="Search">
            <% end %>
          </li>
      
          
          <div  class="float-right">
          <li><%= button_to "logout", {controller: 'sessions', action: "destroy", method: :post}, {class: ' btn btn-primary  my-2 my-sm-0'} %></li>
          </div>
        </ul>
         
      </div>
    </nav>
  <%end%>

    <%= yield %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/posts/_edit_form.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<div class="container-fluid">
   <div class="row no-gutter">
      <div class="d-none d-md-flex col-md-2 col-lg-4 bg-image-new"></div>
      <div class="col-md-5 col-lg-6">
         <div class="login d-flex align-items-center py-5">
            <div class="container ">
               <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                     <%= render 'error'%><br>
                     <br>
                     <h1>Edit post</h1>
                     <%= form_for @post do |f| %> 
                     <div class="form-group has-error">
                        <label for="slug">Title <span class="require">*</span> <small>(Add a title)</small></label>
                        <%=f.text_field :title, class:"form-control"%>
                     </div>
                     <div class="form-group">
                        <label for="title">Description <span class="require">*</span></label>
                        <%=f.text_field :description, class:"form-control"%>
                     </div>
                     <div class="form-group">
                        <label for="description">Content</label>
                        <%=f.text_area :content, class:"form-control", cols: "30", rows: "10"%>
                     </div>
                     <%= f.label :language %><br>
                     <%= f.collection_select :language_id, @languages, :id, :name %><br>
                     <br>
                     <%= f.fields_for :tags do |tag_form| %>
                     <%= tag_form.label "add tag" %><br>
                     <%= tag_form.text_field :name %>
                     <br/>
                     <% end %>
                     <br>
                     <strong> Choose tags: </strong><br>
                     <br>
                     <%= f.collection_select(:tag_ids, @tags, :id, :name, {:prompt => "All tags "}, {:multiple => true})%><br>
                     <br>
                     <%= button_to "Edit post", {controller: 'posts', action: "create", method: :post}, {class: "btn-lg btn-primary btn-login 
                        text-uppercase font-weight-bold mb-2"} %> <br> 
                     <a href="/posts"> <%= button_to "Back to posts", {class: "btn-lg btn-primary btn-login 
                        text-uppercase font-weight-bold mb-2"} %> <br> </a>
                     <%end%>
                  </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
</div>

app/views/posts/_error.html.erb
<% if flash[:errors] %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(flash["errors"].count , "error") %>
      occurred:
    </h2>
 
    <% flash["errors"].each do |msg| %>
      <%= "#{msg}"%><br>
    <% end %>
 
  </div>

<% end %>

app/views/posts/_form.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<div class="container-fluid">
   <div class="row no-gutter">
      <div class="d-none d-md-flex col-md-2 col-lg-4 bg-image-new"></div>
      <div class="col-md-5 col-lg-6">
         <div class="login d-flex align-items-center py-5">
            <div class="container ">
               <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                     <%= render 'error'%><br>
                     <br>
                     <h1>Create post</h1>
                     <%= form_for @post do |f| %> 
                     <div class="form-group has-error">
                        <label for="slug">Title <span class="require">*</span> <small>(Add a title)</small></label>
                        <%=f.text_field :title, class:"form-control"%>
                     </div>
                     <div class="form-group">
                        <label for="title">Description <span class="require">*</span></label>
                        <%=f.text_field :description, class:"form-control"%>
                     </div>
                     <div class="form-group">
                        <label for="description">Content</label>
                        <%=f.text_area :content, class:"form-control", cols: "30", rows: "10"%>
                     </div>
                     <%= f.label :language %><br>
                     <%= f.collection_select :language_id, @languages, :id, :name %><br>
                     <br>
                     <%= f.fields_for :tags do |tag_form| %>
                     <%= tag_form.label "add tag" %><br>
                     <%= tag_form.text_field :name %>
                     <br/>
                     <% end %>
                     <br>
                     <strong> Choose tags: </strong><br>
                     <br>
                     <%= f.collection_select(:tag_ids, @tags, :id, :name, {:prompt => "All tags "}, {:multiple => true})%><br>
                     <br>
                     <%= button_to "Save post", {controller: 'posts', action: "create", method: :post}, {class: "btn-lg btn-primary btn-login 
                        text-uppercase font-weight-bold mb-2"} %> <br> 
                     <a href="/posts"> <%= button_to "Back to posts", {class: "btn-lg btn-primary btn-login 
                        text-uppercase font-weight-bold mb-2"} %> <br> </a>
                     <%end%>
                  </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
</div>

app/views/posts/edit.html.erb
<%= render 'edit_form'%>

app/views/posts/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= link_to "Author", posts_path(sort: "author") %></th>
      <th scope="col"><%= link_to "Title", posts_path(sort: "title") %></th>
      <th scope="col"><%= link_to "Language", posts_path(sort: "language") %></th>
      <th scope="col">Tags</th>
      <th scope="col"><%= link_to "Likes", posts_path(sort: "likes") %></th>
    </tr>
  </thead>
  <tbody>
  <%@posts.each_with_index do |p, i|%>
    <tr>
      <th scope="row"><%=i+1%></th>
      <td><%=p.user.name%></td>
      <td><%=link_to p.title, post_path(p)%></td>
      <td><%=p.language.name%></td>
      <td><%=p.show_tags%></td>
      <td><%=p.likes.count%></td>
    </tr>
    <%end%>
  </tbody>
</table>
<%if @posts.blank?%>
  <p>No posts to show here</p>
<%end%>

app/views/posts/new.html.erb
<%= render 'form'%>

app/views/posts/show.html.erb
<%= render 'error'%>
<% if flash[:notice] %>
  <h1><div class="notice"><%= flash[:notice] %></div></h1>
<% end %>


<div class="container-show">
   <%# <div class="row"> %>
   <!-- Post Content Column -->
      <div class="col-lg-8 ">
            <!-- Title -->
            <h1><%= @post.title%></h1>
            <div class="date-post">
                          <p><%=@post.created_at.strftime("%d-%B-%Y  -  %H:%M")%></p>
                        </div>
             <!-- Author -->
               <div class="lead">
                  by:
                    <strong> <%= link_to @post.user.name, user_path(@post.user)%></strong>  
                    </div><br>
                    
                        <div class="lead">
                           Language: 
                             <strong><%= @post.language.name%></strong><br>
                          
                               </div>
                                  <hr>
                                  <!-- tags--->
                                      <p class="lead">
                                          Tags:
                                           <a href="#"><%=@post.show_tags %> </a>


                                               <hr>
                                               <div class="lead">
                                              

                                         
                                                <!-- Post description -->
                                                   <h2>description: <br> <h6 class="lead"><%= @post.description%></h6>
                                                   
                                                     <hr>
                                                         <h2>Content: <h2><br>
                                                              <div>
                                                               <h6> <%= @post.content%></h6>
                                                                  <hr>       
                                                                 <% pre_like = @post.likes.find { |like| like.user_id == @user.id} %>
                                                                  <% if pre_like %>
                                                                    <%= button_to '👎', post_like_path(@post, pre_like), method: :delete, class:"btn btn-primary mb-2", title:"unlike this post"  %>
                                                                      </div>
                                                                       <h6><%=@post.likes.count%> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'  %></h6>
                                                                         <% else %>
                                                                             <%= button_to '👍', post_likes_path(@post), method: :post, class:"btn btn-primary mb-2", title:"like this post" %>                                       
                                                                                <h6><%=@post.likes.count%> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'  %></h6>
                                                                                  <%end%>
                                                                                  <br>

                                                                              <%if (@post.user_id == @user.id) || @user.is_admin%>
                                                                                <%= button_to  "Delete Post", @post, method: :delete, class:"btn btn-primary mb-2", title:"delete this post",data: {confirm: "Are you sure you want to delete this post?"} %>
                                                                                 <%= button_to  "Edit", edit_post_path(@post), method: :get, class:"btn btn-primary mb-2", title:"like this post"   %>
                                                                              <%end%>

                                            <br>
       
            <h5 class="card-header">Leave a Comment:</h5>
              <div class="card-body">
                 <%= form_tag ({controller: 'posts', action: 'add_comment', method: 'post'}) do %>
                    <div class="form-group">
                                     <textarea name="comment" rows="3" id="comment_text_area" cols="30" rows="10" class="form-control"></textarea><br>
                                        </div>
                                        <input type=submit value='add comment' class="btn btn-primary">
                                           <% end %><br><br>
                                        </div>
                                          </div>
                                                </div>
                                              </div>
                  <div class="media mb-4">
                    <img class="d-flex mr-3 rounded-circle" src="" alt="">
                         <div class="media-body"> 
                        <h1> Comments:</h1>                                      
                            <%@post.comments.each do |c|%>
                                <h4><%= link_to "#{c.user.name}", user_path(c.user) %></h4> <%= "#{c.created_at.strftime("%d-%B-%Y  -  %H:%M")}"%><br>
                                    <p><%=c.content%></p><br>
                                   
                                       <br>
                                         <%end%>
                                              </div>
                                            
                                                  
                                                 </div>

                                                    </div>
                                                      </div>  

app/views/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User</th>
      <th scope="col"># of Posts</th>
    </tr>
  </thead>
  <tbody>
  <%@users.each_with_index do |u, i|%>
    <tr>
      <th scope="row"><%=i+1%></th>
      <td><%=link_to u.name, user_path(u)%></td>
      <td><%=u.posts.count%></td>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
             
               <div class="container mb-2 btn btn-block ">
                <h3 class="login-heading mb-4">Welcome to Code Pad</h3>
                <%= form_for @user, controller: 'users', action: 'create' do |f| %>
                  <div class="form-label-group">
                    <%= f.label :name %><br>
                    <br>
                      <%= f.text_field :name %>
                  </div>
                  
                  <div class="form-label-group">
                  <label> <%= f.label :password %></label><br>
                  <br>
                      <%= f.password_field :password %>
                  </div>

                  <div class="form-label-group">
                    <%= f.label :password_confirmation %><br>
                    <br>
                     <%= f.password_field :password_confirmation %>
                </div><br>
                <div >
                 <%= button_to "Sign up", {controller: 'users', action: "create", method: :post}, {class: "btn-lg btn-primary btn-login 
                text-uppercase font-weight-bold mb-2"} %><br>
                <p>Already member??<p>
                   <a href="/login"><button class= 'btn-lg btn-primary btn-login 
                text-uppercase font-weight-bold mb-2'> Sign in </button> </a>
           
                </div>
              <% end %>
              </div>
          
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="center-title", id=user_name_show_page>
      User: <%= @user.name %></h1>
      </h1>
     

   <%if @posts.size > 0%>
   <h4 class="center-title">Posts by this user:<h4>
   <br>
   <div class="custom-container">
      <% @posts.each do |post|%>
  <div class="grid-item">
          <h3><%=  post.title%></h3>
          <a href=><%= link_to "View the post", post_path(post)%></a><br>
          </div>
          <%end%>
          </div>
                <%else%>
             <p id=no_post_user_page> This user doesn't have any post</p>
                <div  class="">
          </div>
    <%end%>    
        
      </div>
   
    </div>
    </div>